name: Merge Conflict Labeler

on:
  pull_request_target:
    types: [ synchronize ]

jobs:
  label:
    name: 'Merge conflict labeling'
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'tycrek/ass' }}
    steps:
      - uses: eps1lon/actions-label-merge-conflict@releases/2.x
        if: ${{ github.event_name == 'push' || github.event_name == 'pull_request_target'}}
        with:
          dirtyLabel: 'merge conflict'
          commentOnDirty: '**[AUTOMATED MESSAGE]** 🔴 This Pull Request has merge conflicts. Please resolve the conflicts so the PR can be successfully reviewed and merged.'
          commentOnClean: '**[AUTOMATED MESSAGE]** 🟢 Conflicts have been resolved.'
          repoToken: "${{ secrets.GH_TOKEN }}"
